dunglas/vulcain

.github/workflows/cd.yml, .github/workflows/ci.yml, gateway/gateway_test.go
=> Add CI workflow on GitHub Actions

docs/cache.md
Hi 👋 
I was reading when I've seen a small syntax error in the `cache.md` file, hope it helps 😄
=> [DOC] fix on cache syntax

fixtures/static/index.html, fixtures/static/main.js
tested locally :heavy_check_mark:
=> Improve async loop

spec/vulcain.md
=> spec: reword the part about preload hints

README.md
=> docs: add treeware license

CONTRIBUTING.md, spec/vulcain.md
=> spec: minor formatting fixes

gateway/gateway.go, gateway/gateway_test.go
=> fix: the Prefer header wasn't property read from the request

cmd/vulcain/.goreleaser.yml
=> fix: fix GoReleaser config

CONTRIBUTING.md, example_test.go, pusher.go, server.go, vulcain.go, vulcain_test.go
This allows more performance optimizations and better errors handling.
=> feat: improve the public API

docs/gateway/install.md, docs/gateway/openapi.md
=> docs: Fix typos

caddy/caddy.go, caddy/go.mod, vulcain.go
=> docs: add a description to the Caddy module

docs/gateway/install.md
docs: Fix gateway docker url for https
=> docs: update gateway/install.md

caddy/go.mod, caddy/go.sum, go.mod, go.sum
=> fix: Go Modules dependencies

server_test.go, test-push/composer.json, test-push/composer.lock, test-push/tester.php
Switch to Amp instead of curl client.
=> test: unskip Server Push tests

.github/workflows/cd.yml, .github/workflows/ci.yml
=> ci: bump deps

.github/workflows/cd.yml, .github/workflows/ci.yml
=> ci: replace deprecated option

.github/workflows/cd.yml, .github/workflows/ci.yml, .goreleaser.yml, caddy/go.mod, go.mod
=> chore: upgrade to Go 1.21 and fix CI

.github/CODE_OF_CONDUCT.md, .github/workflows/cd.yml, CONTRIBUTING.md, README.md, docs/graphql.md, spec/vulcain.md
=> ci: skip Docker login when not a tag

.goreleaser.yml, Caddyfile, Dockerfile, docs/gateway/caddy.md, docs/gateway/install.md, docs/help.md, legacy.Dockerfile
Build a Caddy-based binary and update the docs.
=> feat: build Caddy binary

caddy/go.mod, caddy/go.sum, go.mod, go.sum, openapi.go
=> chore: upgrade kin-openapi to 0.122

caddy/vulcain/main.go
Backport of https://github.com/caddyserver/caddy/pull/5711
=> chore: sync automaxprocs logging with upstream Caddy

docs/help.md
docs: update stackoverflow tag in documentation
=> Update stackoverflow tag in help.md

docs/gateway/caddy.md
=> fix: fix typo in caddy.md

Caddyfile, caddy/caddy.go, caddy/caddy_test.go, caddy/fixtures/Caddyfile, docs/gateway/caddy.md
See https://github.com/caddyserver/caddy/pull/5865.
=> feat: use the new RegisterDirectiveOrder to simplify config

docs/cache.md
=> docs: update link for xkey module
